In [13]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [15]:
print(a*3)

[ 3  6  9 12 15]


In [17]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [41]:
b=np.array([1,2,3,6,4,5])
r_array=b[::-1]
print(type(r_array))

<class 'numpy.ndarray'>


In [43]:
r_array=np.flip(b)
r_array

array([5, 4, 6, 3, 2, 1])

In [47]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.bincount(x)
print(y)
m=max(y)
print(m)
for i in range(len(y)):
    if(m==y[i]):
        print(i)

[0 5 2 1 1 1]
5
1


In [53]:
import numpy as np
y=np.array([1,1,1,2,3,4,2,4,3,3])
unique,counts=np.unique(y,return_counts=True)
most_frequent_value=unique[np.argmax(counts)]
indices=np.where(y==most_frequent_value)[0]
print("Most Frequent Value:",most_frequent_value)
print("Indices:",indices)

Most Frequent Value: 1
Indices: [0 1 2]


In [107]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[0])
print(arr[:,1])
print(arr[:,0])
print(arr[2])

20
[10 20 30]
[20 50 80]
[10 40 70]
[70 80 90]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [61]:
print(arr[2][0])

70


In [105]:
rohini=np.linspace(10,100,25)
print(rohini)
print(np.ndim(rohini))
print(np.shape(rohini))
print(len(rohini))
print(rohini.dtype)
print(rohini.nbytes)
print(rohini.reshape(1,25))
print(rohini.T)
print(np.shape(rohini))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)


In [127]:
ucs420_rohini=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
m=np.mean(ucs420_rohini)
print("Mean:",m)
x=np.median(ucs420_rohini)
print("Median:",x)
y=np.max(ucs420_rohini)
print("Max:",y)
z=np.min(ucs420_rohini)
print("Min:",z)
reshaped_ucs420_rohini=ucs420_rohini.reshape(4,3)
print(reshaped_ucs420_rohini)
resized_ucs420_rohini=np.resize(reshaped_ucs420_rohini,(2,3))
print(resized_ucs420_rohini)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
